#pragma once

enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    PLUS, MINUS, STAR, SLASH, PERIOD,
    EQUAL, COMMA, SEMICOLON, GREATER, LESS,
    IDENTIFIER, NUMBER, INT, BOOL, VOID,
    IF, ELSE, WHILE, TRUE, FALSE, RETURN,
    ERROR, END_OF_FILE
};
